### ISSUE TITLE
Propose a new rule. EOL - LF

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/quality-criteria#16]
## Problem

Different operating systems have different settings for the EOL.  That is why, add recommendations for that.

## Proposal

Make a specific guide on how to setup `LF` for EOL on different operating systems.

**Comment by liza-veis** [comment]
Not sure if this should be in the quality criteria, but totally agree that final code in repos and especially team projects should be in `lf` only

**Comment by what1s1ove** [comment]
Hello team, 

Thinking about this issue, I remembered that not all files can be written in this format. Because of this, we definitely cannot make this rule mandatory for all files. 

Also, agreed with Lisa. I do not think that this rule should be right in the quality criteria. Perhaps it could be part of `editorconfig` and we should consider having `editorconfig` in all projects (although it is already everywhere. Just to restrict it).
